// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct GetPokemonSpeciesInput {
    #[allow(missing_docs)] // documentation missing in model
    pub name: std::string::String,
}
impl GetPokemonSpeciesInput {
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(&self) -> &str {
        use std::ops::Deref;
        self.name.deref()
    }
}
impl std::fmt::Debug for GetPokemonSpeciesInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("GetPokemonSpeciesInput");
        formatter.field("name", &self.name);
        formatter.finish()
    }
}
/// See [`GetPokemonSpeciesInput`](crate::input::GetPokemonSpeciesInput).
pub mod get_pokemon_species_input {

    /// A builder for [`GetPokemonSpeciesInput`](crate::input::GetPokemonSpeciesInput).
    #[derive(std::default::Default, std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
    pub struct Builder {
        pub(crate) name: std::option::Option<std::string::String>,
    }
    impl Builder {
        #[allow(missing_docs)] // documentation missing in model
        pub fn name(mut self, input: impl Into<std::string::String>) -> Self {
            self.name = Some(input.into());
            self
        }
        #[allow(missing_docs)] // documentation missing in model
        pub fn set_name(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.name = input;
            self
        }
        /// Consumes the builder and constructs a [`GetPokemonSpeciesInput`](crate::input::GetPokemonSpeciesInput).
        pub fn build(
            self,
        ) -> Result<crate::input::GetPokemonSpeciesInput, aws_smithy_http::operation::BuildError>
        {
            Ok(crate::input::GetPokemonSpeciesInput {
                name: self.name.unwrap_or_default(),
            })
        }
    }
}
impl GetPokemonSpeciesInput {
    /// Creates a new builder-style object to manufacture [`GetPokemonSpeciesInput`](crate::input::GetPokemonSpeciesInput).
    pub fn builder() -> crate::input::get_pokemon_species_input::Builder {
        crate::input::get_pokemon_species_input::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct EmptyOperationInput {}
impl std::fmt::Debug for EmptyOperationInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("EmptyOperationInput");
        formatter.finish()
    }
}
/// See [`EmptyOperationInput`](crate::input::EmptyOperationInput).
pub mod empty_operation_input {

    /// A builder for [`EmptyOperationInput`](crate::input::EmptyOperationInput).
    #[derive(std::default::Default, std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
    pub struct Builder {}
    impl Builder {
        /// Consumes the builder and constructs a [`EmptyOperationInput`](crate::input::EmptyOperationInput).
        pub fn build(
            self,
        ) -> Result<crate::input::EmptyOperationInput, aws_smithy_http::operation::BuildError>
        {
            Ok(crate::input::EmptyOperationInput {})
        }
    }
}
impl EmptyOperationInput {
    /// Creates a new builder-style object to manufacture [`EmptyOperationInput`](crate::input::EmptyOperationInput).
    pub fn builder() -> crate::input::empty_operation_input::Builder {
        crate::input::empty_operation_input::Builder::default()
    }
}

#[allow(missing_docs)] // documentation missing in model
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct GetServerStatisticsInput {}
impl std::fmt::Debug for GetServerStatisticsInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("GetServerStatisticsInput");
        formatter.finish()
    }
}
/// See [`GetServerStatisticsInput`](crate::input::GetServerStatisticsInput).
pub mod get_server_statistics_input {

    /// A builder for [`GetServerStatisticsInput`](crate::input::GetServerStatisticsInput).
    #[derive(std::default::Default, std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
    pub struct Builder {}
    impl Builder {
        /// Consumes the builder and constructs a [`GetServerStatisticsInput`](crate::input::GetServerStatisticsInput).
        pub fn build(
            self,
        ) -> Result<crate::input::GetServerStatisticsInput, aws_smithy_http::operation::BuildError>
        {
            Ok(crate::input::GetServerStatisticsInput {})
        }
    }
}
impl GetServerStatisticsInput {
    /// Creates a new builder-style object to manufacture [`GetServerStatisticsInput`](crate::input::GetServerStatisticsInput).
    pub fn builder() -> crate::input::get_server_statistics_input::Builder {
        crate::input::get_server_statistics_input::Builder::default()
    }
}
