// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[derive(std::clone::Clone, std::cmp::PartialEq)]
pub struct FlavorText {
    /// The localized flavor text for an API resource in a specific language.
    pub flavor_text: std::string::String,
    /// The language this name is in.
    pub language: crate::model::Language,
}
impl FlavorText {
    /// The localized flavor text for an API resource in a specific language.
    pub fn flavor_text(&self) -> &str {
        use std::ops::Deref;
        self.flavor_text.deref()
    }
    /// The language this name is in.
    pub fn language(&self) -> &crate::model::Language {
        &self.language
    }
}
impl std::fmt::Debug for FlavorText {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut formatter = f.debug_struct("FlavorText");
        formatter.field("flavor_text", &self.flavor_text);
        formatter.field("language", &self.language);
        formatter.finish()
    }
}
/// See [`FlavorText`](crate::model::FlavorText).
pub mod flavor_text {

    /// A builder for [`FlavorText`](crate::model::FlavorText).
    #[derive(std::default::Default, std::clone::Clone, std::cmp::PartialEq, std::fmt::Debug)]
    pub struct Builder {
        pub(crate) flavor_text: std::option::Option<std::string::String>,
        pub(crate) language: std::option::Option<crate::model::Language>,
    }
    impl Builder {
        /// The localized flavor text for an API resource in a specific language.
        pub fn flavor_text(mut self, input: impl Into<std::string::String>) -> Self {
            self.flavor_text = Some(input.into());
            self
        }
        /// The localized flavor text for an API resource in a specific language.
        pub fn set_flavor_text(mut self, input: std::option::Option<std::string::String>) -> Self {
            self.flavor_text = input;
            self
        }
        /// The language this name is in.
        pub fn language(mut self, input: crate::model::Language) -> Self {
            self.language = Some(input);
            self
        }
        /// The language this name is in.
        pub fn set_language(mut self, input: std::option::Option<crate::model::Language>) -> Self {
            self.language = input;
            self
        }
        /// Consumes the builder and constructs a [`FlavorText`](crate::model::FlavorText).
        pub fn build(
            self,
        ) -> Result<crate::model::FlavorText, aws_smithy_http::operation::BuildError> {
            Ok(
                crate::model::FlavorText {
                    flavor_text: self.flavor_text
                        .unwrap_or_default()
                    ,
                    language: self.language
                        .ok_or(
                            aws_smithy_http::operation::BuildError::MissingField { field: "language", details: "language was not specified but it is required when building FlavorText" }
                        )?
                    ,
                }
            )
        }
    }
}
impl FlavorText {
    /// Creates a new builder-style object to manufacture [`FlavorText`](crate::model::FlavorText).
    pub fn builder() -> crate::model::flavor_text::Builder {
        crate::model::flavor_text::Builder::default()
    }
}

/// Supported languages for FlavorText entries.
#[derive(
    std::clone::Clone,
    std::cmp::Eq,
    std::cmp::Ord,
    std::cmp::PartialEq,
    std::cmp::PartialOrd,
    std::fmt::Debug,
    std::hash::Hash,
)]
pub enum Language {
    /// American English.
    English,
    /// Español.
    Spanish,
    /// Italiano.
    Italian,
    /// 日本語。
    Japanese,
}
#[derive(Debug, PartialEq, Eq, Hash)]
pub struct LanguageUnknownVariantError(String);
impl std::convert::TryFrom<&str> for Language {
    type Error = LanguageUnknownVariantError;
    fn try_from(s: &str) -> Result<Self, <Language as std::convert::TryFrom<&str>>::Error> {
        match s {
            "en" => Ok(Language::English),
            "es" => Ok(Language::Spanish),
            "it" => Ok(Language::Italian),
            "jp" => Ok(Language::Japanese),
            _ => Err(LanguageUnknownVariantError(s.to_owned())),
        }
    }
}
impl std::convert::From<LanguageUnknownVariantError>
    for aws_smithy_http_server::rejection::RequestRejection
{
    fn from(e: LanguageUnknownVariantError) -> Self {
        Self::EnumVariantNotFound(Box::new(e))
    }
}
impl std::convert::From<LanguageUnknownVariantError> for aws_smithy_json::deserialize::Error {
    fn from(e: LanguageUnknownVariantError) -> Self {
        Self::custom(format!("unknown variant {}", e))
    }
}
impl std::error::Error for LanguageUnknownVariantError {}
impl std::fmt::Display for LanguageUnknownVariantError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
impl std::str::FromStr for Language {
    type Err = LanguageUnknownVariantError;
    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        Language::try_from(s)
    }
}
impl Language {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            Language::English => "en",
            Language::Spanish => "es",
            Language::Italian => "it",
            Language::Japanese => "jp",
        }
    }
    /// Returns all the `&str` values of the enum members.
    pub fn values() -> &'static [&'static str] {
        &["en", "es", "it", "jp"]
    }
}
impl AsRef<str> for Language {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
